// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn5kOoEj_BDIaYxc3QA267Z6fyU_cNa9o',
    appId: '1:519381249779:web:92925f883ac03145c91186',
    messagingSenderId: '519381249779',
    projectId: 'skor-hodimlar',
    authDomain: 'skor-hodimlar.firebaseapp.com',
    storageBucket: 'skor-hodimlar.firebasestorage.app',
    measurementId: 'G-E7RDBPMKP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTjAEW_4KTcKl_V5kyjeq4R5x11ieYHgU',
    appId: '1:519381249779:android:a207de027f69ffddc91186',
    messagingSenderId: '519381249779',
    projectId: 'skor-hodimlar',
    storageBucket: 'skor-hodimlar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZJ3-eJTs8gc1KFsu4f0wr3n5DCuQW_ys',
    appId: '1:519381249779:ios:105772bf6bf4d86cc91186',
    messagingSenderId: '519381249779',
    projectId: 'skor-hodimlar',
    storageBucket: 'skor-hodimlar.firebasestorage.app',
    iosBundleId: 'uz.skor.hodimlar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZJ3-eJTs8gc1KFsu4f0wr3n5DCuQW_ys',
    appId: '1:519381249779:ios:9930394f171ef385c91186',
    messagingSenderId: '519381249779',
    projectId: 'skor-hodimlar',
    storageBucket: 'skor-hodimlar.firebasestorage.app',
    iosBundleId: 'com.example.skoreHodimlar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn5kOoEj_BDIaYxc3QA267Z6fyU_cNa9o',
    appId: '1:519381249779:web:7daf9108cddf3276c91186',
    messagingSenderId: '519381249779',
    projectId: 'skor-hodimlar',
    authDomain: 'skor-hodimlar.firebaseapp.com',
    storageBucket: 'skor-hodimlar.firebasestorage.app',
    measurementId: 'G-X2FWE0PR4C',
  );
}
